return {
  Normal = { bg = C.black, fg = C.white },
  ColorColumn = { bg = D.light_black, fg = none},
  CurSearch = { bg = cursor, fg = none},
  CursorColumn = { bg = D.light_black, fg = none },
  CursorLine = { bg = D.light_black, fg = none },
  NonText = { bg = C.black, fg = C.grey },
  ErrorMsg = { bg = D.dark_red, fg = none },
  WinSeparator = { fg = C.grey, bg = none },
  Folded = { bg = D.Light_black, fg = C.grey },
  FoldColumn = { bg = C.black, fg = C.white },
  SignColumn = { bg = none, fg = none },
  IncSearch = { bg = cursor, fg = C.black },
  Search = { bg = C.red, fg = C.black },
  lineNr = { bg = none, fg = D.grey1 },
  CursorlineNr = { bg = none, fg = C.grey },
  MatchParen = { bg = C.white, fg = C.black },
  Question = { bg = none, fg = C.green },
  Cursor = { bg = red, fg = C.green },
}
