return {
  a = { [[:/[^\d0-\d127]<cr>]], "search non-ASCII chars" },
  g = { "<cmd>TSHighlightCapturesUnderCursor<cr>", "treesitter playground" },
  k = { "<cmd>set nu!<Bar> set rnu!<cr>", "toggle line numbers" },
  n = { "<cmd>tabnew<cr>", "open new project(s)"},
  c = { "<cmd>cclose<cr>", "close quickfix window"},
  i = { "go to ith tab (project)" }, -- doc only
  t = {
    name = "Toggle",
    p = { "<cmd>set cursorline!<Bar> set cursorcolumn!<cr>", "cursor lc" },
    l = { "<cmd>set list!<cr>", "non printable" },
    c = { "<cmd>lua global_params.cmp.toggle = not global_params.cmp.toggle<cr>", "cmp" },
    i = { "<cmd>IndentBlanklineToggle<cr>", "indent line" },
    C = { "<cmd>ColorizerToggle<cr>", "colorizer" },
    h = { "<cmd>TSBufToggle highlight <Bar> TSBufToggle rainbow<cr>", "treesitter" },
    f = { "<cmd>NvimTreeOpen<cr>", "file explorer" },
    b = { function() vim.opt.showtabline = (vim.go.showtabline == 0 and 2 or 0) end, "tabline" },
    t = { "<cmd>ToggleTerm<cr>", "open terminal"},
  },
  f = {
    name = "Finder",
    f = { "<cmd> lua require('telescope.builtin').find_files() <cr>", "find files" },
    a = { "<cmd> lua require('telescope.builtin').find_files({hidden=true}) <cr>", "find hidden" },
    g = { "<cmd> lua require('telescope.builtin').live_grep() <cr>", "live grep" },
    b = { "<cmd> lua require('telescope.builtin').buffers({only_cwd=true,ignore_current_buffer=true })<cr>", "find buffers" },
    h = { "<cmd> lua require('telescope.builtin').help_tags() <cr>", "help page" },
    o = { "<cmd> lua require('telescope.builtin').oldfiles() <cr>", "find oldfiles" },
    p = { "<cmd> lua require('telescope').extensions.projects.projects{}<cr>", "find project" },
  },
  L = {
    name = "Latex",
    c = { "<plug>(vimtex-compile)", "continuous compile" },
    C = { "<plug>(vimtex-stop)", "stop compilation" },
    s = { "<plug>(vimtex-compile-ss)", "single compile" },
    v = { "<plug>(vimtex-view)", "view PDF" },
    x = { "<plug>(vimtex-clean)", "clean auxiliary files" },
  },
  d = {
    name = "Doc Only",
    o = { 
      name = "Other",
      ["<C-\\>"] = { "redraw in the middle (insert)" },
      ["<C-c>"] = { "capitalise word (insert)" },
      ["<C-p>"] = { "toggle terminal" },
      J = { "move text block down (visual)" },
      K = { "move text block up (visual)" },
      T = { "split window at bottom (normal) "},
      S = { "split window on right (normal) "},
    },
    t = {
      name = "Telescope",
      ["<C-j>"] = { "select next" },
      ["<C-k>"] = { "select previous" },
      ["<C-n>"] = { "history next" },
      ["<C-p>"] = { "history prev" },
      ["<M-p>"] = { "toggle preview" },
      ["<C-u>"] = { "scroll preview up" },
      ["<C-d>"] = { "scroll preview down" },
      ["<C-s>"] = { "vertical spilt" },
      ["<C-t>"] = { "horizontal spilt" },
      ["<C-x>"] = { "tab spilt" },
      ["<C-w>"] = { "change working directory" },
      ["<C-/>"] = { "see all available mappings" },
    },
    f = {
      name = "File Explorer",
      ["?"] = { "see all available mappings" },
      ["<C-]>"] = { "change directory" },
      u = { "directory up" },
      ["<C-f>"] = { "create file (or directory trailing '/')" },
      ["<C-r>"] = { "rename" },
      c = { "copy file" },
      y = { "copy file name" },
      Y = { "copy relative path" },
    },
  },
}
